// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieznxwqzdndgqrjxaiwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllem54d3F6ZG5kZ3FyanhhaXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjMyNjIsImV4cCI6MjA3MTkzOTI2Mn0.rAD0fuA2eLtAUCXdfCMe2EaDvOOwtLUX34fPw3C82P8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});